const busData = [
    { no: "1 A", route: "PGI, ISBT-17, Railway Station, Manimajra, PGI" },
    { no: "2 A", route: "Manimajra, Sec-26, PGI, Sarangpur, Dhanas, Manimajra" },
    { no: "2 D", route: "PGI, ISBT-17, Railway Station, IT Park" },
    { no: "2 F", route: "PGI, ISBT-17, Panchkula Sec-20" },
    { no: "3", route: "Mauli Jagran, Railway Station, ISBT-17, PGI" },
    { no: "4 A/C", route: "ISBT-43, Aroma, ISBT-17, PGI, Dhanas, Maloya" },
    { no: "5 A/C", route: "Ram Darbar, Sec-32, ISBT-17, PGI, Maloya, ISBT-43" },
    { no: "7 A/C", route: "ISBT-17, Sec-24, Maloya, ISBT-43, Ram Darbar" },
    { no: "8", route: "Mohali Railway Station, ISBT-43, PGI" },
    { no: "9 A/C", route: "Mansa Devi, Manimajra, Sec-17, Mohali" },
    { no: "10", route: "ISBT-43, Tribune Chowk, Mansa Devi" },
    { no: "17", route: "ISBT-43, Aroma, Elante Mall, Airport" },
    { no: "20", route: "Chandigarh, ISBT-43, Sohana, Landran, Kharar" },
    { no: "22", route: "ISBT-43, ISBT-17, Railway Station, IT Park" },
    { no: "24", route: "ISBT-43, Aroma, PGI" },
    { no: "25", route: "Chandigarh, Khuda Alisher, Mullanpur, Sialwa" },
    { no: "26", route: "Dhanas, ISBT-17, Airport, Zirakpur, Dhakoli" },
    { no: "28", route: "ISBT-43, Aroma, PGI, Dhanas" },
    { no: "30", route: "ISBT-43, Aroma, Manimajra, Nada Sahib" },
    { no: "32", route: "ISBT-17, Tribune Chowk, Zirakpur, Dera Bassi" },
    { no: "34", route: "PGI, ISBT-17, Zirakpur, Derabassi" },
    { no: "35", route: "ISBT-17, Mohali Ph-6, Balongi, Kharar" },
    { no: "38", route: "ISBT-17, ISBT-43, New Airport" },
    { no: "39", route: "Mohali Ph-11, ISBT-43, ISBT-17, PGI" },
    { no: "71", route: "ISBT-43, ISBT-17, Mansa Devi, Saketri" },
    { no: "79", route: "PGI, ISBT-17, Tribune Chowk, Chhatbir Zoo" },
    { no: "80", route: "Zirakpur, Elante Mall, PGI" },
    { no: "82", route: "Airport, Hallo Majra, Mansa Devi" },
    { no: "143", route: "Dhanas, PGI, ISBT-17, Airport" },
    { no: "206", route: "ISBT-43, ISBT-17, Manimajra, IT Park" },
    { no: "213", route: "Kharar, Mohali, ISBT-43, ISBT-17, Mansa Devi" },
    { no: "242", route: "Landran, Sohana, ISBT-43, ISBT-17, PGI" }
];

// Extracted unique locations from all images
const locations = [
    "Airport", "Aroma Chowk", "Balongi", "Chhatbir Zoo", "Dera Bassi", 
    "Dhakoli", "Dhanas", "Elante Mall", "Hallo Majra", "ISBT-17", 
    "ISBT-43", "IT Park", "Jagatpura", "Kharar", "Khuda Alisher", 
    "Landran", "Manimajra", "Mansa Devi", "Mauli Jagran", "Mohali", 
    "Nada Sahib", "New Airport", "Panchkula Sec-20", "PGI", 
    "Railway Station", "Ram Darbar", "Saketri", "Sarangpur", 
    "Sohana", "Tribune Chowk", "Zirakpur"
].sort();
